'use client';
import Link from 'next/link';
import { motion, useReducedMotion } from 'framer-motion';
import { Arrow } from '@/components/icons';
import { Footer, Header } from '@/components/site-shell';
import { stats } from '@/content/site';
const offers = [
  ['École de tennis', 'Apprendre les bases, prendre confiance et aimer jouer dès 3 ans.', '/tennis'],
  ['Tennis adultes', 'Des cours adaptés à chaque niveau, dans une ambiance accueillante.', '/tennis'],
  ['Fête le Mur', 'Le tennis comme outil d’éducation, de découverte et de partage.', '/fete-le-mur'],
];
export default function Home() { const reduced = useReducedMotion(); return <><Header/><main>
  <section className="hero-home relative isolate flex min-h-[720px] items-end overflow-hidden px-5 pb-14 pt-32 text-white"><div className="tennis-court absolute inset-0 -z-10"/><motion.div initial={reduced ? false : {opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{duration:.75}} className="mx-auto w-full max-w-7xl"><p className="eyebrow text-[#72d68b]">TENNIS CLUB MUNICIPAL DE GOUSSAINVILLE</p><h1 className="mt-5 max-w-5xl text-balance text-5xl font-black leading-[.9] tracking-[-.07em] sm:text-7xl lg:text-8xl">Le tennis<br/><em className="font-medium text-[#72d68b]">pour tous.</em></h1><p className="mt-6 max-w-xl text-lg leading-8 text-white/80">Depuis 1983, le TCMG fait vivre le tennis à Goussainville, avec exigence, plaisir et convivialité.</p><div className="mt-9 flex flex-wrap gap-3"><Link className="button button-green" href="/le-club">Découvrir le club <Arrow/></Link><Link className="button button-ghost" href="/contact">Nous contacter</Link></div></motion.div></section>
  <section className="border-y border-slate-100 bg-white px-5 py-8"><div className="mx-auto grid max-w-7xl grid-cols-2 gap-6 md:grid-cols-4">{stats.map(s=><div key={s.label} className="border-l-2 border-[#2FA84F] pl-4"><strong className="block text-2xl font-black tracking-[-.05em] text-[#0057B8]">{s.value}</strong><span className="text-sm font-semibold text-slate-600">{s.label}</span></div>)}</div></section>
  <section className="px-5 py-24"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.86fr_1.14fr]"><div><p className="eyebrow text-[#2FA84F]">LE CLUB</p><h2 className="headline mt-4">Jouer, progresser, se retrouver.</h2></div><div><p className="text-lg leading-8 text-slate-600">École de tennis, pratique adultes, compétition ou premiers échanges : chaque membre trouve sa place au TCMG. Notre équipe accompagne les joueurs avec attention, dans un club où la progression va de pair avec le plaisir de se retrouver.</p><Link href="/le-club" className="text-link mt-7 text-[#0057B8]">Connaître le club <Arrow/></Link></div></div></section>
  <section className="bg-[#edf6f0] px-5 py-24"><div className="mx-auto max-w-7xl"><p className="eyebrow text-[#2FA84F]">NOS PRATIQUES</p><h2 className="headline mt-4">Une place pour chaque envie.</h2><div className="mt-12 grid gap-4 md:grid-cols-3">{offers.map(([title,text,href], index)=><motion.article whileHover={reduced ? undefined : {y:-6}} key={title} className="offer-card"><span>0{index+1}</span><h3>{title}</h3><p>{text}</p><Link href={href}>Explorer <Arrow/></Link></motion.article>)}</div></div></section>
  <section className="bg-[#0057B8] px-5 py-24 text-white"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2"><div><p className="eyebrow text-[#72d68b]">FÊTE LE MUR</p><h2 className="headline mt-4">Bien plus qu’un terrain de jeu.</h2></div><div><p className="text-lg leading-8 text-white/80">Le tennis devient un outil d’éducation, de découverte et de partage. Activités nature, jardinage, cuisine, sorties et jeux collectifs prolongent l’expérience au-delà du court.</p><Link href="/fete-le-mur" className="button button-green mt-8">Découvrir Fête le Mur <Arrow/></Link></div></div></section>
  <section className="px-5 py-24"><div className="mx-auto max-w-7xl rounded-[2rem] bg-[#062a59] p-8 text-white md:p-14"><p className="eyebrow text-[#72d68b]">UN PROJET, UNE QUESTION ?</p><div className="mt-5 flex flex-wrap items-end justify-between gap-8"><h2 className="max-w-3xl text-4xl font-black tracking-[-.06em] md:text-6xl">Votre prochain<br/><em className="font-medium">échange</em> commence ici.</h2><Link href="/contact" className="button button-green">Nous rejoindre <Arrow/></Link></div></div></section>
 </main><Footer/></>; }
