'use client';
import Link from 'next/link';
import { motion, useScroll, useTransform } from 'framer-motion';
import { Footer, Header, Mark, SocialRail } from '@/components/site-shell';

const programs=[
  {n:'01',title:'École de tennis',copy:'Des premiers rebonds aux premiers matchs. Dès 4 ans, chacun trouve son rythme.',href:'/ecole-de-tennis',image:'photo-1595435934249-5df7ed86e1c0'},
  {n:'02',title:'Tennis adultes',copy:'Cours, jeu libre et rendez-vous du soir : le tennis qui s’adapte à votre vie.',href:'/adultes',image:'photo-1530915365347-e35b749a0381'},
  {n:'03',title:'Compétition',copy:'Des équipes engagées et une énergie collective à porter haut.',href:'/competition',image:'photo-1622279457486-62dcc4a431d6'},
];
const stories=[['18 SEPT.','Les inscriptions d’hiver sont ouvertes','Les créneaux de la saison sont prêts : il ne manque plus que vous.'],['07 SEPT.','Une rentrée pleine d’énergie','Une journée portes ouvertes, des échanges et beaucoup de sourires.'],['28 AOÛT','TCMG × Fête le Mur','Le court devient un espace de confiance pour la jeunesse.']];
function Count({value,label}:{value:string,label:string}) { return <div className="stat"><strong>{value}</strong><span>{label}</span></div> }
export default function Home(){const {scrollY}=useScroll();const y=useTransform(scrollY,[0,800],[0,180]); return <><Header/><main><section className="hero"><motion.div style={{y}} className="hero-image"/><div className="hero-shade"/><div className="court-lines"/><div className="hero-orb orb-one"/><div className="hero-orb orb-two"/><div className="hero-content"><motion.div initial={{opacity:0,scale:.6,rotate:-14}} animate={{opacity:1,scale:1,rotate:0}} transition={{type:'spring',duration:1.1}} className="hero-mark"><Mark/></motion.div><motion.p initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{delay:.25}} className="eyebrow light">TENNIS CLUB MUNICIPAL DE GOUSSAINVILLE</motion.p><motion.h1 initial={{opacity:0,y:44}} animate={{opacity:1,y:0}} transition={{delay:.36,duration:.8}}><span>LE JEU</span><em>NOUS RASSEMBLE.</em></motion.h1><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.58}} className="hero-actions"><Link className="button button-primary" href="/reservation">Réserver un terrain <b>↗</b></Link><Link className="button button-glass" href="/le-club">Découvrir le club</Link></motion.div></div><div className="hero-bottom"><p>Depuis 1968 — Goussainville</p><a href="#club">Faire défiler <span>↓</span></a></div></section><SocialRail/>
<section id="club" className="intro section"><div className="section-tag">01 / L’ESPRIT TCMG</div><div className="intro-grid"><h2>PLUS QU’UN<br/><i>CLUB.</i></h2><div><p className="intro-copy">Au TCMG, le tennis se vit sans filtre : l’intensité d’un match, la joie d’un progrès, le plaisir de se retrouver. Un club ouvert à toutes les ambitions.</p><Link href="/le-club" className="text-link">Notre histoire <span>→</span></Link></div></div><div className="stats"><Count value="400+" label="licenciés"/><Count value="8" label="courts"/><Count value="32" label="équipes engagées"/><Count value="1" label="même passion"/></div></section>
<section className="programs"><div className="section programs-head"><div><p className="eyebrow green">JOUER À SON RYTHME</p><h2>UN TERRAIN,<br/><i>MILLE ÉLANS.</i></h2></div><Link href="/ecole-de-tennis" className="round-link">Voir tous les programmes <span>↗</span></Link></div><div className="program-grid">{programs.map((p)=><Link className="program-card" href={p.href} key={p.title}><div className="program-photo" style={{backgroundImage:`url(https://images.unsplash.com/${p.image}?auto=format&fit=crop&w=1000&q=85)`}}/><div className="program-overlay"/><span className="program-number">{p.n}</span><div className="program-copy"><h3>{p.title}</h3><p>{p.copy}</p><b>Explorer <span>→</span></b></div></Link>)}</div></section>
<section className="fete"><div className="fete-image"/><div className="fete-content"><p className="eyebrow light">FÊTE LE MUR × TCMG</p><h2>LE TENNIS<br/>COMME <i>TREMPLIN.</i></h2><p>Sur nos courts, le sport devient un langage commun, un outil de confiance et un chemin pour avancer.</p><Link className="button button-white" href="/fete-le-mur">Découvrir le programme <b>↗</b></Link></div><div className="fete-stamp">ICI<br/>TOUT<br/>COMMENCE</div></section>
<section className="news section"><div className="news-head"><div><p className="eyebrow blue">DANS LE JEU</p><h2>LA VIE DU<br/><i>CLUB.</i></h2></div><Link href="/actualites" className="text-link">Toutes les actualités <span>→</span></Link></div><div className="story-list">{stories.map((s,i)=><article className="story" key={s[1]}><span className="story-index">0{i+1}</span><div><p>{s[0]}</p><h3>{s[1]}</h3><span>{s[2]}</span></div><Link href="/actualites" aria-label={s[1]}>↗</Link></article>)}</div></section>
<section className="cta section"><div><p className="eyebrow light">LA SAISON VOUS ATTEND</p><h2>ENTREZ<br/>DANS LE <i>JEU.</i></h2></div><Link href="/contact" className="button button-white">Nous rejoindre <b>↗</b></Link></section></main><Footer/></>}
