'use client';
import { ChangeEvent, FormEvent, useEffect, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import type { AdminData } from '@/lib/admin-store';

const initial: AdminData = { events: [], schedules: '', prices: '', products: [], contact: { phone: '', email: '', address: '', instagram: '', facebook: '' }, photos: [] };
const sections = ['Photos', 'Événements', 'Horaires', 'Tarifs', 'Organigramme', 'Boutique Training Addict', 'Réseaux sociaux', 'Contact'];
const staff = [['Rudy Coco', 'Coach'], ['Grégoire Coulaud', 'Coach'], ['Cédric Pouget', 'Coach'], ['Nathan Dufait', 'Éducateur'], ['Mehdi Benabdelmoumene', 'Éducateur'], ['Ekin Zincir', 'Éducateur'], ['Nassim Saifi', 'Éducateur']];
const bureau = ['Sandrine Poirier — Présidente', 'Philippe Matos — Vice-président', 'Rosa Boumadi — Trésorière', 'Murielle Fufait — Secrétaire', 'Gia Han Lam — Responsable Communication', 'Céline Decrawer — Responsable Événementiel', 'Savanah Thirion — Représentante de Section'];

export function AdminDashboard() {
  const [data, setData] = useState(initial); const [active, setActive] = useState('Photos'); const [notice, setNotice] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { fetch('/api/admin/data').then(r => r.json()).then(setData).catch(() => setNotice('Impossible de joindre Vercel KV.')).finally(() => setLoading(false)); }, []);
  async function save(next = data) { const response = await fetch('/api/admin/data', { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify(next) }); if (response.ok) { setData(next); setNotice('Modifications enregistrées.'); } else setNotice('Enregistrement impossible : configurez Vercel KV.'); }
  async function upload(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; const form = new FormData(); form.append('file', file); form.append('category', event.target.dataset.category ?? 'Club'); setNotice('Téléversement…'); const response = await fetch('/api/admin/photos', { method: 'POST', body: form }); const result = await response.json(); if (response.ok) { setData(d => ({ ...d, photos: [result, ...d.photos] })); setNotice('Photo ajoutée.'); } else setNotice(result.error); event.target.value = ''; }
  function updateContact(field: keyof AdminData['contact'], value: string) { setData(d => ({ ...d, contact: { ...d.contact, [field]: value } })); }
  function addEvent(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const next = { ...data, events: [...data.events, { id: crypto.randomUUID(), title: String(form.get('title')), date: String(form.get('date')), description: String(form.get('description')) }] }; save(next); event.currentTarget.reset(); }
  function addProduct(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const next = { ...data, products: [...data.products, { id: crypto.randomUUID(), name: String(form.get('name')), price: String(form.get('price')), stock: String(form.get('stock')) }] }; save(next); event.currentTarget.reset(); }
  const remove = (kind: 'events' | 'products', id: string) => save({ ...data, [kind]: data[kind].filter(item => item.id !== id) });
  return <main className="admin-shell min-h-screen"><header className="border-b border-white/10 px-5 py-5 text-white"><div className="mx-auto flex max-w-7xl items-center justify-between"><div><p className="eyebrow text-[#72d68b]">TCMG</p><b className="text-xl">Console d’administration</b></div><button onClick={() => fetch('/api/admin/logout', { method: 'POST' }).then(() => location.assign('/admin/login'))} className="text-sm font-bold text-white/75">Déconnexion</button></div></header><div className="mx-auto grid max-w-7xl gap-6 px-5 py-8 lg:grid-cols-[230px_1fr]"><aside className="admin-nav">{sections.map(name => <button key={name} onClick={() => setActive(name)} className={active === name ? 'active' : ''}>{name}</button>)}</aside><section className="admin-panel"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow text-[#2FA84F]">GESTION TCMG</p><h1 className="mt-2 text-3xl font-black tracking-[-.055em] text-[#062a59]">{active}</h1></div>{notice && <span className="rounded-full bg-[#edf6f0] px-3 py-2 text-xs font-bold text-[#19753a]">{notice}</span>}</div>{loading ? <p className="mt-12 text-slate-500">Chargement…</p> : <AnimatePresence mode="wait"><motion.div key={active} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -10 }} className="mt-8">{active === 'Photos' && <Photos photos={data.photos} upload={upload} />}{active === 'Événements' && <Events events={data.events} onAdd={addEvent} onRemove={id => remove('events', id)} />}{active === 'Horaires' && <TextEditor title="Horaires" value={data.schedules} onChange={schedules => setData({ ...data, schedules })} onSave={() => save()} />}{active === 'Tarifs' && <TextEditor title="Tarifs" value={data.prices} onChange={prices => setData({ ...data, prices })} onSave={() => save()} />}{active === 'Boutique Training Addict' && <Products products={data.products} onAdd={addProduct} onRemove={id => remove('products', id)} />}{active === 'Organigramme' && <Organisation />}{active === 'Réseaux sociaux' && <Contact data={data.contact} update={updateContact} save={() => save()} socialOnly />}{active === 'Contact' && <Contact data={data.contact} update={updateContact} save={() => save()} />}</motion.div></AnimatePresence>}</section></div></main>;
}

function Photos({ photos, upload }: { photos: AdminData['photos']; upload: (e: ChangeEvent<HTMLInputElement>) => void }) { return <div><p className="admin-help">Ajoutez une image depuis votre téléphone. Elle sera conservée dans Vercel Blob et affichée immédiatement.</p><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{['Club', 'Fête le Mur', 'Événements', 'Boutique'].map(category => <label key={category} className="admin-photo-add"><input className="sr-only" data-category={category} type="file" accept="image/*" onChange={upload} /><span>＋</span><b>Ajouter une photo</b><small>{category}</small></label>)}</div><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-3">{photos.map(photo => <figure key={photo.id} className="admin-photo"><img src={photo.url} alt={photo.name} /><figcaption>{photo.category}</figcaption></figure>)}</div></div> }
function Events({ events, onAdd, onRemove }: { events: AdminData['events']; onAdd: (e: FormEvent<HTMLFormElement>) => void; onRemove: (id: string) => void }) { return <div className="space-y-5"><form onSubmit={onAdd} className="admin-form"><input required name="title" placeholder="Nom de l’événement"/><input required name="date" type="date"/><textarea name="description" placeholder="Description"/><button className="button button-blue">Ajouter</button></form>{events.map(event => <article className="admin-row" key={event.id}><div><b>{event.title}</b><p>{event.date} · {event.description}</p></div><button onClick={() => onRemove(event.id)} className="admin-delete">Supprimer</button></article>)}</div> }
function TextEditor({ title, value, onChange, onSave }: { title: string; value: string; onChange: (value: string) => void; onSave: () => void }) { return <div><p className="admin-help">Mettez à jour les informations qui seront publiées sur le site.</p><textarea className="admin-textarea mt-6" value={value} onChange={e => onChange(e.target.value)} aria-label={title}/><button onClick={onSave} className="button button-blue mt-4">Enregistrer</button></div> }
function Products({ products, onAdd, onRemove }: { products: AdminData['products']; onAdd: (e: FormEvent<HTMLFormElement>) => void; onRemove: (id: string) => void }) { return <div className="space-y-5"><form onSubmit={onAdd} className="admin-form"><input required name="name" placeholder="Produit"/><input required name="price" placeholder="Prix"/><input required name="stock" placeholder="Stock"/><button className="button button-blue">Ajouter le produit</button></form>{products.map(product => <article className="admin-row" key={product.id}><div><b>{product.name}</b><p>{product.price} · Stock : {product.stock}</p></div><button onClick={() => onRemove(product.id)} className="admin-delete">Supprimer</button></article>)}</div> }
function Organisation() { return <div><p className="admin-help">Le bureau est conservé à l’identique. Les trois derniers membres sportifs utilisent l’avatar TCMG par défaut.</p><h2 className="admin-subtitle">Bureau</h2><div className="grid gap-2 sm:grid-cols-2">{bureau.map(member => <div className="admin-row" key={member}>{member}</div>)}</div><h2 className="admin-subtitle">Sportif</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{staff.map(([name, role], index) => <article className="admin-person" key={name}><span className={index > 3 ? 'default-avatar' : 'person-avatar'}>{index > 3 ? 'TCMG' : name.split(' ').map(x => x[0]).join('')}</span><b>{name}</b><small>{role}</small></article>)}</div></div> }
function Contact({ data, update, save, socialOnly = false }: { data: AdminData['contact']; update: (field: keyof AdminData['contact'], value: string) => void; save: () => void; socialOnly?: boolean }) { const fields: [keyof AdminData['contact'], string][] = socialOnly ? [['instagram', 'Instagram'], ['facebook', 'Facebook']] : [['phone', 'Téléphone'], ['email', 'E-mail'], ['address', 'Adresse'], ['instagram', 'Instagram'], ['facebook', 'Facebook']]; return <div className="admin-form">{fields.map(([key, label]) => <label key={key}>{label}<input value={data[key]} onChange={e => update(key, e.target.value)} /></label>)}<button onClick={save} className="button button-blue">Enregistrer</button></div> }
