'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { Brand } from './brand';
import { Menu } from './icons';
import { club } from '@/content/site';
const links = [['Le Club', '/le-club'], ['Tennis', '/tennis'], ['Padel', '/padel'], ['Fête le Mur', '/fete-le-mur'], ['Boutique', '/boutique'], ['Galerie', '/galerie']];
export function Header() { const [open, setOpen] = useState(false); const [scrolled, setScrolled] = useState(false); useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 28); onScroll(); window.addEventListener('scroll', onScroll, { passive: true }); return () => window.removeEventListener('scroll', onScroll); }, []); return <header className={`fixed inset-x-0 top-0 z-50 transition-all duration-500 ${scrolled ? 'border-b border-white/10 bg-[#111426]/85 backdrop-blur-xl' : ''}`}><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5"><Brand /><nav className="hidden items-center gap-5 text-[13px] font-bold text-white/75 xl:flex" aria-label="Navigation principale">{links.map(([label, href]) => <Link className="hover:text-[#d8ff57]" href={href} key={href}>{label}</Link>)}<Link className="rounded-full bg-[#d8ff57] px-4 py-2 text-[#111426] hover:bg-white" href="/contact">Nous rejoindre</Link></nav><button onClick={() => setOpen(!open)} aria-expanded={open} aria-label="Ouvrir le menu" className="grid h-10 w-10 place-items-center rounded-full border border-white/30 text-white xl:hidden"><Menu /></button></div><AnimatePresence>{open && <motion.nav initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }} exit={{ opacity: 0, height: 0 }} className="overflow-hidden bg-[#111426] px-5 xl:hidden">{links.concat([['Contact', '/contact']]).map(([label, href]) => <Link onClick={() => setOpen(false)} className="block border-t border-white/10 py-4 text-sm font-bold text-white" href={href} key={href}>{label}</Link>)}</motion.nav>}</AnimatePresence></header>; }
export function Footer() { return <footer className="bg-[#111426] px-5 py-14 text-white"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-[1.6fr_1fr_1fr] "><div><Brand /><p className="mt-5 max-w-sm text-sm leading-6 text-white/55">Le tennis, le padel et l’engagement collectif au cœur de Goussainville.</p></div><div><p className="eyebrow text-[#d8ff57]">NOUS TROUVER</p><a href={club.mapsUrl} className="mt-4 block text-sm leading-7 text-white/70 hover:text-white">{club.address}</a><a href={`tel:${club.phone}`} className="block text-sm leading-7 text-white/70 hover:text-white">{club.phoneLabel}</a><a href={`mailto:${club.email}`} className="block text-sm leading-7 text-white/70 hover:text-white">{club.email}</a></div><div><p className="eyebrow text-[#d8ff57]">SUIVEZ-NOUS</p><div className="mt-4 flex gap-3"><a aria-label="Instagram" className="social" href={club.social.instagram}>ig</a><a aria-label="TikTok" className="social" href={club.social.tiktok}>tk</a><a aria-label="Facebook" className="social" href={club.social.facebook}>fb</a></div><p className="mt-7 text-xs text-white/35">© {new Date().getFullYear()} TCMG</p></div></div></footer>; }
