import type { Metadata } from 'next'; import Link from 'next/link'; import { notFound } from 'next/navigation'; import { Header, Footer } from '@/components/site-shell'; import { Arrow } from '@/components/icons';
const pages:Record<string,{title:string;kicker:string,lead:string,image:string,features:string[]}>={
 'le-club':{kicker:'LE TCMG',title:'Un club à vivre, bien au-delà du terrain.',lead:'Depuis Goussainville, nous rassemblons toutes les générations autour d’un même plaisir : jouer, progresser et partager.',image:'photo-1554068865-24cecd4e34b8',features:['8 courts pour jouer toute l’année','Une équipe de bénévoles passionnée','Des rendez-vous qui créent du lien']},
 'ecole-de-tennis':{kicker:'ÉCOLE DE TENNIS',title:'Faire naître l’envie de jouer.',lead:'Des premiers pas aux premiers matchs, notre équipe pédagogique accompagne chaque enfant avec attention et énergie.',image:'photo-1595435934249-5df7ed86e1c0',features:['Baby tennis dès 4 ans','Groupes adaptés à chaque niveau','Stages pendant les vacances']},
 adultes:{kicker:'TENNIS ADULTES',title:'Le bon rythme, le bon partenaire.',lead:'Cours collectifs, jeu libre, tournois internes : composez votre saison de tennis à votre image.',image:'photo-1530915365347-e35b749a0381',features:['Cours loisirs et perfectionnement','Créneaux jeu libre','Animations toute la saison']},
 competition:{kicker:'COMPÉTITION',title:'Jouer collectif. Viser plus haut.',lead:'Nos équipes portent les couleurs du TCMG avec ambition, solidarité et sourire.',image:'photo-1622279457486-62dcc4a431d6',features:['Équipes jeunes et adultes','Accompagnement des compétiteurs','Tournois et interclubs']},
 'fete-le-mur':{kicker:'FÊTE LE MUR',title:'Le tennis comme tremplin.',lead:'Un programme d’inclusion par le sport, pour permettre à chaque jeune de trouver sa place et de tracer sa trajectoire.',image:'photo-1595435934249-5df7ed86e1c0',features:['Initiations gratuites','Accompagnement éducatif','Une ouverture sur le monde']},
 actualites:{kicker:'ACTUALITÉS',title:'Les histoires qui font le club.',lead:'Résultats, événements, portraits et rendez-vous : restez au plus près de la vie du TCMG.',image:'photo-1622279457486-62dcc4a431d6',features:['Inscriptions hiver ouvertes','Retour sur la journée portes ouvertes','Les équipes préparent les interclubs']},
 galerie:{kicker:'GALERIE',title:'L’énergie du TCMG, en images.',lead:'Des regards, des échanges et des victoires. Plongez dans les moments qui animent notre club.',image:'photo-1554068865-24cecd4e34b8',features:['Sur le court','Dans les tribunes','En dehors du jeu']},
 boutique:{kicker:'BOUTIQUE',title:'Portez les couleurs du TCMG.',lead:'La collection du club arrive bientôt. Équipez-vous pour jouer, encourager et vous retrouver.',image:'photo-1595435934249-5df7ed86e1c0',features:['Textile club','Accessoires de jeu','Précommandes bientôt ouvertes']},
 contact:{kicker:'CONTACT',title:'On se retrouve sur le court ?',lead:'Une question, une inscription ou simplement l’envie de nous rencontrer ? Écrivez-nous.',image:'photo-1530915365347-e35b749a0381',features:['Parc des Sports, Goussainville','contact@tcmg.fr','01 39 88 00 00']}
};
export function generateStaticParams(){return Object.keys(pages).map(slug=>({slug}));} export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=pages[slug];return p?{title:p.kicker,description:p.lead}:{};}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params; const p=pages[slug];if(!p)return notFound();return <><Header/><main><section className="relative isolate min-h-[70vh] overflow-hidden bg-[#071120] px-5 pb-16 pt-40 text-white"><div className="absolute inset-0 -z-20 bg-cover bg-center opacity-55" style={{backgroundImage:`url(https://images.unsplash.com/${p.image}?auto=format&fit=crop&w=1800&q=90)`}}/><div className="absolute inset-0 -z-10 bg-gradient-to-t from-[#071120] via-[#071120]/65 to-[#071120]/25"/><div className="mx-auto max-w-7xl"><p className="text-xs font-bold tracking-[.23em] text-[#9ac7ff]">{p.kicker}</p><h1 className="mt-5 max-w-4xl text-balance text-5xl font-black leading-[.92] tracking-[-.06em] md:text-7xl">{p.title}</h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/75">{p.lead}</p></div></section><section className="px-5 py-20"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold tracking-[.2em] text-[#0A8F2E]">L’ESSENTIEL</p><div className="mt-8 grid gap-4 md:grid-cols-3">{p.features.map((f,i)=><div className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm" key={f}><p className="text-sm font-bold text-[#0066D6]">0{i+1}</p><h2 className="mt-14 text-2xl font-black tracking-[-.04em]">{f}</h2></div>)}</div><div className="mt-16 rounded-[2rem] bg-[#0066D6] p-8 text-white md:p-12"><h2 className="max-w-xl text-3xl font-black tracking-[-.04em] md:text-5xl">Envie de faire partie de l’aventure ?</h2><Link href="/contact" className="mt-7 inline-flex items-center gap-3 rounded-full bg-white px-6 py-4 text-sm font-bold text-[#0066D6]">Parlons-en <Arrow/></Link></div></div></section></main><Footer/></>}
