'use client';
import Link from 'next/link';
import { use, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { Footer, Header } from '@/components/site-shell';

type Page={kicker:string,title:string,lead:string,image:string,items:string[]};
const pages:Record<string,Page>={
 'le-club':{kicker:'LE TCMG',title:'UN CLUB À VIVRE, BIEN AU-DELÀ DU TERRAIN.',lead:'Un lieu de jeu, de transmission et de rencontres au cœur de Goussainville.',image:'photo-1554068865-24cecd4e34b8',items:['8 courts pour jouer toute l’année','Une équipe de bénévoles engagée','Une maison pour toutes les générations']},
 'ecole-de-tennis':{kicker:'ÉCOLE DE TENNIS',title:'FAIRE NAÎTRE L’ENVIE DE JOUER.',lead:'Des premiers rebonds aux premières victoires, nos moniteurs accompagnent chaque enfant avec exigence et bienveillance.',image:'photo-1595435934249-5df7ed86e1c0',items:['Baby tennis dès 4 ans','Groupes adaptés à chaque niveau','Stages pendant les vacances']},
 adultes:{kicker:'TENNIS ADULTES',title:'LE BON RYTHME. LE BON PARTENAIRE.',lead:'Cours collectifs, jeu libre et animations : composez une saison qui vous ressemble.',image:'photo-1530915365347-e35b749a0381',items:['Loisir & perfectionnement','Créneaux jeu libre','Tournois internes toute l’année']},
 competition:{kicker:'COMPÉTITION',title:'JOUER COLLECTIF. VISER PLUS HAUT.',lead:'Des équipes, des tournois et une ambition partagée sous les couleurs bleu et vert du TCMG.',image:'photo-1622279457486-62dcc4a431d6',items:['Équipes jeunes et adultes','Calendrier des rencontres','Résultats et classements']},
 'fete-le-mur':{kicker:'FÊTE LE MUR',title:'LE TENNIS COMME TREMPLIN.',lead:'Une alliance pour rendre le tennis accessible et faire du sport un levier de confiance.',image:'photo-1595435934249-5df7ed86e1c0',items:['Initiations gratuites','Accompagnement éducatif','Ouverture culturelle et citoyenne']},
 actualites:{kicker:'ACTUALITÉS',title:'LES HISTOIRES QUI FONT LE CLUB.',lead:'Résultats, portraits, rendez-vous : restez au plus près de l’énergie TCMG.',image:'photo-1622279457486-62dcc4a431d6',items:['Inscriptions d’hiver ouvertes','Retour sur les portes ouvertes','Les équipes préparent les interclubs']},
 galerie:{kicker:'GALERIE',title:'L’ÉNERGIE TCMG, EN IMAGES.',lead:'Des regards, des échanges et des victoires. Retrouvez les moments qui font vibrer le club.',image:'photo-1554068865-24cecd4e34b8',items:['Entraînements','Compétitions','Événements du club']},
 boutique:{kicker:'BOUTIQUE TCMG',title:'PORTEZ LES COULEURS DU CLUB.',lead:'Une collection pensée pour le court, les tribunes et tous les jours.',image:'photo-1530915365347-e35b749a0381',items:['Sweats & t-shirts','Polos & vestes','Accessoires']},
 contact:{kicker:'CONTACT',title:'ON SE RETROUVE SUR LE COURT ?',lead:'Une question, une inscription ou l’envie de venir découvrir le club : notre équipe vous répond.',image:'photo-1622279457486-62dcc4a431d6',items:['Parc des Sports, Goussainville','contact@tcmg.fr','01 39 88 00 00']},
 partenaires:{kicker:'PARTENAIRES',title:'GRANDIR, C’EST JOUER COLLECTIF.',lead:'Merci à celles et ceux qui font rayonner le tennis à Goussainville à nos côtés.',image:'photo-1554068865-24cecd4e34b8',items:['Fête le Mur','Marques & équipementiers','Partenaires locaux']},
 reservation:{kicker:'RÉSERVER',title:'VOTRE TERRAIN VOUS ATTEND.',lead:'Réservez votre créneau sur la plateforme officielle Ten’Up, en quelques instants.',image:'photo-1622279457486-62dcc4a431d6',items:['Accès réservé aux adhérents','Réservation via Ten’Up','Besoin d’aide ? Contactez-nous']},
 admin:{kicker:'ESPACE ADMINISTRATEUR',title:'PILOTER LA VIE DU CLUB.',lead:'Un espace simple pour publier, organiser et faire vivre les contenus du TCMG.',image:'photo-1554068865-24cecd4e34b8',items:['Actualités & photos','Résultats à valider','Boutique & événements']},
};
const gallery=['Entraînements','Compétitions','Fête le Mur','Olympiades','Halloween','Tournoi des Familles','Événements'];
const products=[['Sweat club','55 €','Sweats'],['T-shirt match','28 €','T-shirts'],['Polo performance','42 €','Polos'],['Veste équipe','68 €','Vestes'],['Casquette TCMG','22 €','Casquettes'],['Gourde court','18 €','Accessoires']];
function Gallery(){const [selected,setSelected]=useState<string|null>(null);return <section className="detail-section"><div className="album-grid">{gallery.map((g,i)=><button key={g} onClick={()=>setSelected(g)} className="album" style={{backgroundImage:`url(https://images.unsplash.com/photo-${['1595435934249-5df7ed86e1c0','1622279457486-62dcc4a431d6','1554068865-24cecd4e34b8'][i%3]}?auto=format&fit=crop&w=900&q=80)`}}><span>{g}</span><small>Voir l’album ↗</small></button>)}</div><AnimatePresence>{selected&&<motion.div className="lightbox" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setSelected(null)}><button aria-label="Fermer">×</button><h2>{selected}</h2><p>Les images du TCMG — emplacements prêts à recevoir les photos officielles du club.</p></motion.div>}</AnimatePresence></section>}
function Shop(){return <section className="detail-section"><div className="products">{products.map((p,i)=><article className="product" key={p[0]}><div className="product-photo" style={{backgroundImage:`url(https://images.unsplash.com/photo-${['1530915365347-e35b749a0381','1554068865-24cecd4e34b8','1595435934249-5df7ed86e1c0'][i%3]}?auto=format&fit=crop&w=700&q=80)`}}/><p>{p[2]}</p><h3>{p[0]}</h3><strong>{p[1]}</strong><span>Tailles S — XXL · En stock</span><button>Choisir une taille</button></article>)}</div></section>}
function Competition(){return <section className="detail-section comp-grid"><div className="schedule"><p className="eyebrow green">PROCHAINS MATCHS</p><h2>Calendrier compétition</h2><div><b>27 SEP. · 14:00</b><span>TCMG 1 — TC Sarcelles</span><em>Interclubs seniors</em></div><div><b>04 OCT. · 10:00</b><span>TCMG U14 — TC Gonesse</span><em>Championnat jeunes</em></div><Link className="text-link" href="/actualites">Tous les résultats →</Link></div><form className="result-form"><p className="eyebrow blue">MEMBRES</p><h2>Publier un résultat</h2><input placeholder="Joueur / joueuse"/><input placeholder="Score (ex. 6/4 7/5)"/><select defaultValue=""><option value="" disabled>Choisir la compétition</option><option>Interclubs</option><option>Tournoi individuel</option></select><button className="button button-primary">Envoyer pour validation</button></form></section>}
function Contact(){return <section className="detail-section contact-grid"><div className="map"><span>TCMG</span><p>Parc des Sports<br/>Goussainville</p></div><form className="result-form"><p className="eyebrow blue">ÉCRIVEZ-NOUS</p><input placeholder="Votre nom"/><input placeholder="Votre email"/><textarea placeholder="Votre message" rows={4}/><button className="button button-primary">Envoyer <b>↗</b></button></form></section>}
function Partners(){return <section className="detail-section partner-grid">{['Fête le Mur','Babolat','Dunlop','Prince','Mizuno','Artengo'].map((x,i)=><a href="#" className="partner" key={x}><b>{x}</b><span>{i===0?'Le tennis, levier d’égalité.':'Partenaire équipement du TCMG.'}</span><i>↗</i></a>)}</section>}
function Admin(){return <section className="detail-section admin-grid">{['Publier une actualité','Ajouter des photos','Valider les résultats','Gérer la boutique','Programmer un événement','Ajouter un partenaire'].map((x,i)=><button key={x}><span>0{i+1}</span><b>{x}</b><i>↗</i></button>)}</section>}
export default function Page({params}:{params:Promise<{slug:string}>}){const {slug}=use(params);const p=pages[slug];if(!p)return <><Header/><main className="notfound">Page introuvable</main><Footer/></>; const special=slug;return <><Header/><main><section className="page-hero"><div className="page-hero-photo" style={{backgroundImage:`url(https://images.unsplash.com/${p.image}?auto=format&fit=crop&w=2000&q=90)`}}/><div className="page-hero-shade"/><div className="page-hero-content"><p className="eyebrow light">{p.kicker}</p><h1>{p.title}</h1><p>{p.lead}</p>{special==='reservation'&&<a className="button button-primary" href="https://tenup.fft.fr" target="_blank">Accéder à Ten’Up <b>↗</b></a>}</div></section>{special==='galerie'?<Gallery/>:special==='boutique'?<Shop/>:special==='competition'?<Competition/>:special==='contact'?<Contact/>:special==='partenaires'?<Partners/>:special==='admin'?<Admin/>:<section className="detail-section"><p className="section-tag">L’ESSENTIEL</p><div className="feature-grid">{p.items.map((x,i)=><article key={x}><span>0{i+1}</span><h2>{x}</h2></article>)}</div><div className="information"><h2>Le TCMG, c’est l’envie de faire du tennis une expérience qui compte.</h2><Link className="button button-primary" href="/contact">Nous contacter <b>↗</b></Link></div></section>}</main><Footer/></>}
