import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Arrow } from '@/components/icons';
import { Footer, Header } from '@/components/site-shell';
import { club, orderUrl, products } from '@/content/site';
const pages: Record<string, { kicker:string; title:string; lead:string; intro:string; items:{title:string; text:string}[] }> = {
  'le-club': { kicker:'LE CLUB', title:'Un club qui rassemble.', lead:'Un lieu de jeu, de progrès et de rencontres au cœur de Goussainville.', intro:'Au TCMG, l’école de tennis, les adultes et la compétition se côtoient dans un esprit simple : donner à chacun les moyens de progresser et le plaisir de partager le court.', items:[{title:'Une équipe engagée',text:'Un accompagnement attentif pour faire évoluer chaque joueur à son rythme.'},{title:'Jouer toute l’année',text:'Quatre courts couverts et deux courts Green Set pour vivre le tennis au fil des saisons.'},{title:'Une vie de club',text:'Des rencontres, des échanges et une convivialité qui font la force du TCMG.'}] },
  tennis: { kicker:'TENNIS', title:'Le plaisir de chaque échange.', lead:'Une pratique adaptée à tous les âges, tous les niveaux et toutes les ambitions.', intro:'La technique, le plaisir de jouer et la progression sont au cœur de chaque séance. Dès le mini-tennis, l’équipe du TCMG accompagne les joueurs dans leurs premiers échanges comme dans leurs projets de compétition.', items:[{title:'Mini-tennis',text:'Une découverte ludique du tennis dès 3 ans.'},{title:'Jeunes',text:'Grandir dans le jeu, développer ses repères et son autonomie.'},{title:'Adultes',text:'Des cours et des temps de jeu pour progresser à son rythme.'},{title:'Compétition',text:'Un suivi structuré pour celles et ceux qui aiment se dépasser.'}] },
  'fete-le-mur': { kicker:'FÊTE LE MUR', title:'Grandir au-delà du court.', lead:'Le tennis devient un outil d’éducation, de découverte et de partage.', intro:'Fête le Mur élargit l’horizon des jeunes. Tennis, nature, jardin, cuisine, sorties et jeux collectifs deviennent autant d’occasions d’apprendre, de se rencontrer et de prendre confiance.', items:[{title:'Tennis enfants',text:'Le jeu, le mouvement et le collectif comme point de départ.'},{title:'Activités nature',text:'Observer, explorer et prendre soin de son environnement.'},{title:'Jardinage & cuisine',text:'Semer, récolter, préparer et partager.'},{title:'Padel découverte',text:'Une initiation découverte organisée dans le cadre de Fête le Mur — le TCMG reste un club de tennis.'},{title:'Piscine, sorties & jeux',text:'Des moments pour découvrir, s’amuser et créer des souvenirs.'}] },
  galerie: { kicker:'GALERIE', title:'Les moments qui nous rassemblent.', lead:'Tennis, coaching, enfants, événements et Fête le Mur : découvrez la vie du club.', intro:'Les images du TCMG racontent les entraînements, les rencontres et toutes les expériences vécues ensemble. Utilisez les filtres pour parcourir les différents univers du club.', items:[{title:'Tennis',text:'Entraînements, matchs et premiers échanges.'},{title:'Enfants',text:'L’énergie et les progrès des jeunes joueurs.'},{title:'Coaching',text:'Les gestes, les conseils et les encouragements.'},{title:'Événements',text:'Les rendez-vous qui font vivre le club.'},{title:'Fête le Mur',text:'Les découvertes sur et hors des courts.'}] },
  boutique: { kicker:'BOUTIQUE OFFICIELLE', title:'Portez nos couleurs.', lead:'La collection officielle TCMG, en partenariat avec Training Addict.', intro:'Retrouvez les pièces de la collection officielle. Pour commander, choisissez votre article : votre messagerie s’ouvrira avec l’objet de commande déjà renseigné.', items:[] },
  contact: { kicker:'CONTACT', title:'On se retrouve sur le court ?', lead:'Une question, une inscription ou l’envie de découvrir le club ? Parlons-en.', intro:'Retrouvez-nous au Complexe Maurice Bacquet. Notre équipe vous répond par téléphone ou par e-mail.', items:[] },
};
export function generateStaticParams(){return Object.keys(pages).map(slug=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=pages[slug];return p?{title:p.kicker,description:p.lead}:{};}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=pages[slug];if(!p)notFound(); const contact=slug==='contact'; return <><Header/><main><section className="page-hero px-5 pb-20 pt-36 text-white"><div className="mx-auto max-w-7xl"><p className="eyebrow text-[#72d68b]">{p.kicker}</p><h1 className="mt-5 max-w-4xl text-balance text-5xl font-black leading-[.9] tracking-[-.07em] md:text-8xl">{p.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/80">{p.lead}</p></div></section><section className="px-5 py-20"><div className="mx-auto max-w-7xl"><p className="max-w-3xl text-lg leading-8 text-slate-600">{p.intro}</p>{p.items.length>0&&<div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{p.items.map((item,i)=><article key={item.title} className="feature-card"><span>0{i+1}</span><h2>{item.title}</h2><p>{item.text}</p></article>)}</div>}{slug==='boutique'&&<><div className="mt-14 flex items-center gap-3 text-sm font-bold text-[#0057B8]"><span className="training-dot">TA</span> En partenariat avec Training Addict</div><div className="product-grid mt-8">{products.map(product=><article key={product} className="product-card"><span>OFFICIEL TCMG</span><h2>{product}</h2><a href={orderUrl(product)}>Commander <Arrow/></a></article>)}</div></>}{contact&&<><div className="mt-14 grid gap-4 md:grid-cols-3"><a className="contact-card" href={club.mapsUrl} target="_blank" rel="noreferrer"><b>Adresse</b>{club.address.map(line=><span key={line}>{line}</span>)}</a><a className="contact-card" href={`tel:${club.phone}`}><b>Téléphone</b><span>{club.phoneLabel}</span></a><a className="contact-card" href={`mailto:${club.email}`}><b>E-mail</b><span>{club.email}</span></a></div><iframe className="mt-8 h-[400px] w-full rounded-3xl border-0" title="Carte du Complexe Maurice Bacquet" loading="lazy" src="https://www.google.com/maps?q=Complexe%20Maurice%20Bacquet%20All%C3%A9e%20du%205%20D%C3%A9cembre%2095190%20Goussainville&output=embed"/></>}<div className="mt-16 rounded-[2rem] bg-[#edf6f0] p-8 md:p-12"><p className="eyebrow text-[#2FA84F]">TCMG</p><h2 className="mt-4 max-w-2xl text-3xl font-black tracking-[-.05em] text-[#062a59] md:text-5xl">Une même passion, une place pour chacun.</h2><Link href="/contact" className="button button-blue mt-8">Nous contacter <Arrow/></Link></div></div></section></main><Footer/></>;}
